name: Deploy Application

on:
  push:
    path:
      - '!README.md'
      - '!storage/**'
      - '**.blade'
    branches:
      - 'master'
      - 'main'
      - 'sonbt'
      - '!dev/**'
  pull_request:
    type: [opened,reopened,synchronize,labeled,unlabeled]
    path:
    branches:
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: windows-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "do not build"
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello word,today is $TODAY
      - uses: actions/checkout@v3
