name: password
on:
  push:
    branches: [main]
  pull_request:
    type: [opened,reopened,synchronize]
  workflow_dispatch:
jobs:
  Password:
    runs-on: windows-latest
    steps:
      - run: echo This is my secrect ${{ secrects.DB_PASSWORD }}
      - uses: actions/checkout@v2
      - run: npm install
